mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

hosts:
  'mtalk.google.com': 108.177.125.188
  'dl.google.com': 180.163.151.161
  'dl.l.google.com': 180.163.151.161

profile:
  store-selected: false
  
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
  enhanced-mode: redir-host # or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net' 
  nameserver:
    - 119.29.29.29
  
proxies:

proxy-groups:
    
rule-providers:
  Unbreak:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Unbreak.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Unbreak.yaml
    interval: 86400
    
  Adblock:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Adblock.yaml
    url: https://cdn.jsdelivr.net/gh/HotKids/Rules@master/Clash/RuleSet/AD.yaml
    interval: 86400
    
  Advertising:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Advertising.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Guard/Advertising.yaml
    interval: 86400

  Hijacking:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Hijacking.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Guard/Hijacking.yaml
    interval: 86400
    
  Privacy:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Privacy.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Guard/Privacy.yaml
    interval: 86400
    
  Telegram:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Telegram.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Extra/Telegram/Telegram.yaml
    interval: 86400
    
  Apple:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Apple.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Extra/Apple/Apple.yaml
    interval: 86400    

  ATV:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/ATV.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Extra/Apple/TV.yaml
    interval: 86400   
    
  YouTube:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/YouTube.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Video/YouTube.yaml
    interval: 86400
    
  Bahamut:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Bahamut.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Video/Bahamut.yaml
    interval: 86400    

  Disney+:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Disney+.yaml
    url: https://cdn.jsdelivr.net/gh/HotKids/Rules@master/Clash/RuleSet/Disney%2B.yaml
    interval: 86400  

  Disney++:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Disney+.yaml
    url: https://cdn.jsdelivr.net/gh/HotKids/Rules@master/Clash/RuleSet/Disney%2B%2B.yaml
    interval: 86400

  HBO MAX:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/HBO_Max.yaml
    url: https://cdn.jsdelivr.net/gh/HotKids/Rules@master/Clash/RuleSet/HBO_Max.yaml
    interval: 86400
    
  Hulu:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Hulu.yaml
    url: https://cdn.jsdelivr.net/gh/HotKids/Rules@master/Clash/RuleSet/Hulu.yaml
    interval: 86400    

  Prime Video:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Prime_Video.yaml
    url: https://cdn.jsdelivr.net/gh/HotKids/Rules@master/Clash/RuleSet/Prime%20Video.yaml
    interval: 86400 

  Netflix:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Netflix.yaml
    url: https://cdn.jsdelivr.net/gh/HotKids/Rules@master/Clash/RuleSet/Netflix.yaml
    interval: 86400 

  Direct4Myself:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Direct4Myself.yaml
    url: https://cdn.jsdelivr.net/gh/dorokuma/Rules@master/Ruleset/Clash/Direct.yaml
    interval: 86400 

  Proxy4Myself:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Proxy4Myself.yaml
    url: https://cdn.jsdelivr.net/gh/dorokuma/Rules@master/Ruleset/Clash/Proxy.yaml
    interval: 86400
    
  Proxy:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Proxy.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Global.yaml
    interval: 86400   

  China:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/China.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/China.yaml
    interval: 86400   

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./Provider/RuleSet/ChinaIP.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400

rules:
  # Unbreak
  - RULE-SET,Unbreak,âš¡ Direct

  # AdBlock
  - RULE-SET,Adblock,ğŸš« Advertising
  - RULE-SET,Advertising,ğŸš« Advertising
  - RULE-SET,Hijacking,ğŸš« Advertising
  - RULE-SET,Privacy,ğŸš« Advertising
  
  # Global Area Network
 
  # Telegram
  - RULE-SET,Telegram,â˜ï¸ Proxy

  # Apple
  - RULE-SET,Apple,ğŸ Apple
  - RULE-SET,ATV,ğŸ Apple

# Streaming
  - RULE-SET,YouTube,â˜ï¸ Proxy
  - RULE-SET,Bahamut,ğŸï¸ Bahamut
  - RULE-SET,Disney+,ğŸ“º Disney&Netflix
  - RULE-SET,Disney++,ğŸ“º Disney&Netflix 
  - RULE-SET,HBO MAX,ğŸ–¥ï¸ HBO&Hulu 
  - RULE-SET,Hulu,ğŸ–¥ï¸ HBO&Hulu
  - RULE-SET,Prime Video,ğŸ“¹ PrimeVideo   
  - RULE-SET,Netflix,ğŸ“º Disney&Netflix 

# (DNS Cache Pollution) / (IP Blackhole) / (Region-Restricted Access Denied) / (Network Jitter)
  - RULE-SET,Global,â˜ï¸ Proxy

# China Area Network  
  - RULE-SET,China,âš¡ Direct   
  - RULE-SET,Direct4Myself,âš¡ Direct

# Local Area Network
  - IP-CIDR,192.168.0.0/16,âš¡ Direct
  - IP-CIDR,10.0.0.0/8,âš¡ Direct
  - IP-CIDR,172.16.0.0/12,âš¡ Direct
  - IP-CIDR,127.0.0.0/8,âš¡ Direct
  - IP-CIDR,100.64.0.0/10,âš¡ Direct
  - IP-CIDR,224.0.0.0/4,âš¡ Direct
  - IP-CIDR,fe80::/10,âš¡ Direct

# ï¼ˆå¯é€‰ï¼‰ä½¿ç”¨æ¥è‡ª ipipdotnet çš„ ChinaIP ä»¥è§£å†³æ•°æ®ä¸å‡†ç¡®çš„é—®é¢˜ï¼Œä½¿ç”¨ ChinaIP.yaml æ—¶å¯ç¦ç”¨ä¸‹åˆ—ç›´è‡³ï¼ˆåŒ…æ‹¬ï¼‰ã€ŒGEOIP,CNã€è§„åˆ™
  - RULE-SET,ChinaIP,âš¡ Direct

# Final
  - MATCH,â˜ï¸ Proxy
